version: '2.1'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    command: postgres -e POSTGRES_PASSWORD=postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ukpostcodes
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  postgres-init:
    image: postgres:13
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=postgres
      - MINIMAL_DATASET=false
    volumes:
      - ./database-init/schema.sql:/schema.sql
      - ./database-init/data.sql:/data.sql