version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ukpostcodes
    volumes:
      - ./database-init/schema.sql:/schema.sql
      - ./database-init/schema.sql:/data.sql